### ISSUE TITLE
Issue with Altitudes

### ISSUE THREAD

**Issue by coryfail** [Knudian/OpenAIP2GeoJSON#1]
Most geoJSON renders do not like nested arrays or objects, even the github maps show `object:object`. Is it possible for you to pull that information out into its parent array? Maybe just have `top` and `bottom` values that and append the alt type to the end, Example: `"alt_top":"1000 MSL"`

**Comment by Knudian** [comment]
As you might have seen, I did not push a single commit for around 10 months.
Please give me more informations on your issue, or samples, and I will look into it as soon as possible.

**Comment by Knudian** [comment]
Sorry for the late answer, after reading again the documentation, it is implied that all altitudes are "MSL", since all coordinates are given in _WGS84_, so adding those 4 characters seems irrelevant.
